#!/usr/bin/env bash

# run from working directory after creation of dev container

set -euox pipefail

PROFILE="$1"

mkdir -p "$BUILD_DIR"
rm -f "$BUILD_DIR"/CMakeCache.txt

# configure Conan
conan config install /tmp/conan-config
conan profile detect --force

# install dependencies
conan install \
    --build=missing \
    --generator=CMakeDeps \
    --generator=CMakeToolchain \
    --output-folder="$BUILD_DIR" \
    --profile="$PROFILE" \
    .
