#!/usr/bin/env bash

# run from working directory after creation of dev container

set -euox pipefail

PROFILE="$1"
BUILD_TYPE="${2:-'Release'}"

mkdir -p "$BUILD_DIR"
rm -f "$BUILD_DIR"/CMakeCache.txt

# configure Conan
conan config install /tmp/conan-config
conan profile detect --force

# install dependencies
conan install \
    --build=missing \
    --generator=CMakeDeps \
    --generator=CMakeToolchain \
    --output-folder="$BUILD_DIR" \
    --profile="$PROFILE" \
    .

# configure build system
cmake \
    --toolchain "$BUILD_DIR"/conan_toolchain.cmake \
    -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DCMAKE_PREFIX_PATH="$BUILD_DIR" \
    -DCMAKE_TOOLCHAIN_FILE="$BUILD_DIR"/conan_toolchain.cmake \
    -G Ninja \
    -S . \
    "$@"
