#!/usr/bin/env bash

set -euox pipefail

project_dir="$(realpath "$(dirname -- "$0")/..")"
cmake_project_dir="${1:-$project_dir}"

# Generate build system.
cmake \
    --toolchain "$BUILD_DIR"/conan_toolchain.cmake \
    -B "$BUILD_DIR" \
    -DCMAKE_PREFIX_PATH="$BUILD_DIR" \
    -G Ninja \
    -S "$cmake_project_dir"

# Build project.
cmake --build "$BUILD_DIR" --verbose
