#!/usr/bin/env bash

set -euox pipefail

project_dir="$(realpath "$(dirname -- "$0")/..")"
profile="$1"
cmake_project_dir="${2:-$project_dir}"
build_dir="$BUILD_DIR_PARENT"/"$profile"

# Initialize build environment.
# shellcheck source=/dev/null
source "$build_dir"/conanbuild.sh

# Generate build system.
cmake \
    --toolchain "$build_dir"/conan_toolchain.cmake \
    -B "$build_dir" \
    -DCMAKE_PREFIX_PATH="$build_dir" \
    -G Ninja \
    -S "$cmake_project_dir"

# Build project.
cmake --build "$build_dir" --verbose
