#!/usr/bin/env bash

# run from working directory

set -euox pipefail

# Format C++ files.
find . \( -iname '*.h' -o -iname '*.cpp' \) -exec \
  clang-format \
    --Werror \
    --fail-on-incomplete-format \
    -i \
  {} '+'

# Check shell scripts
find . -path ./.git -prune -o -executable -type f -exec \
  shellcheck \
  {} '+'

# If anything has changed, print and fail.
git diff --exit-code
