#!/usr/bin/env bash

# run after invoking workspace/build with the same parameters

set -euox pipefail

profile="${1:-gcc-release}"
build_dir="$BUILD_DIR_PARENT"/"$profile"

# Initialize build environment.
# shellcheck source=/dev/null
source "$build_dir"/conanbuild.sh

# Run unit tests.
ctest --output-on-failure --parallel --test-dir "$build_dir" --verbose
