---
# tests of the checks required by CI, i.e. test tests
name: ci-test

on:
  push:
    branches:
      - '**'
    paths:
      - '.clang-tidy'
      - '.devcontainer/**'
      - '.github/**'
      - 'conanfile.txt'
  workflow_dispatch:

jobs:
  tests:
    name: CI test
    runs-on: ubuntu-latest
    env:
      image_tag: 2
    permissions:
      packages: write

    strategy:
      matrix:
        include:
          - devcontainer: clang-debug
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - devcontainer: clang-release
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "FALSE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "FALSE"
            trigger_warning: "FALSE"

          - devcontainer: clang-test
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - devcontainer: clang-test-fuzzer
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - devcontainer: clang-test-tsan
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "FALSE"
            trigger_tsan: "TRUE"
            trigger_ubsan: "FALSE"
            trigger_warning: "TRUE"

          - devcontainer: clang-tidy
            trigger_clang_tidy: "TRUE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - devcontainer: gcc-debug
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

          - devcontainer: gcc-release
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "FALSE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "FALSE"
            trigger_warning: "FALSE"

          - devcontainer: gcc-test
            trigger_clang_tidy: "FALSE"
            trigger_stdlib: "TRUE"
            trigger_tsan: "FALSE"
            trigger_ubsan: "TRUE"
            trigger_warning: "TRUE"

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run control tests
        uses: devcontainers/ci@v0.3
        env:
          PROJECT_SUBDIRECTORY: ".github/workflows/ci-test"
        with:
          configFile: .devcontainer/${{ matrix.devcontainer }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/ci-test-${{ matrix.devcontainer }}
          imageTag: ${{ env.image_tag }}
          env: |
            TRIGGER_CLANG_TIDY=${{ matrix.trigger_clang_tidy }}
            TRIGGER_STDLIB=${{ matrix.trigger_stdlib }}
            TRIGGER_TSAN=${{ matrix.trigger_tsan }}
            TRIGGER_UBSAN=${{ matrix.trigger_ubsan }}
            TRIGGER_WARNING=${{ matrix.trigger_warning }}
          runCmd: |
            cmake --build $BUILD_DIR --verbose
            ctest --output-on-failure --test-dir $BUILD_DIR --verbose
