---
name: 'C++ test'

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  unit-tests:
    name: test
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      fail-fast: false
      matrix:
        profile:
          - clang-debug
          - clang-release
          - clang-test
          - clang-test-fuzzer
          - clang-test-tsan
          - clang-tidy
          - gcc-debug
          - gcc-release
          - gcc-test

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache build artefacts
        uses: actions/cache@v4
        with:
          key: ${{ matrix.profile }}-${{ hashFiles('conanfile.*') }}
          path: |
            ~/.conan2/p
            ~/build/${{ matrix.profile }}

      - name: Build and run tests
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/johnmcfarlane/simple-cpp
          imageTag: 4
          runCmd: |
            scripts/build ~/build ${{ matrix.profile }}
            scripts/test ~/build ${{ matrix.profile }}
            ls -al ~/.conan2/p
            ls -al ~/build/${{ matrix.profile }}

  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/johnmcfarlane/simple-cpp/lint
          imageTag: 4
          runCmd: scripts/lint
