---
name: 'C++ test'

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  unit-tests:
    name: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    working-directory: /home/tux/build

    strategy:
      fail-fast: false
      matrix:
        profile:
          - clang-debug
          - clang-release
          - clang-test
          - clang-test-fuzzer
          - clang-test-tsan
          - clang-tidy
          - gcc-debug
          - gcc-gcov
          - gcc-release
          - gcc-test

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run tests
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/johnmcfarlane/simple-cpp
          imageTag: 4
          runCmd: |
            scripts/build ~/build ${{ matrix.profile }}
            scripts/test ~/build ${{ matrix.profile }}

      - name: Generate coverage report
        if: ${{ matrix.profile }} == 'gcc-gcov'
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/${{ matrix.profile }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/${{ matrix.profile }}
          imageTag: 3
          runCmd: |
            .devcontainer/gcc-gcov/report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: ${{ matrix.profile }} == 'gcc-gcov'
        with:
          name: coverage-report
          path: ~/build/gcc-gcov/test-coverage.html
          if-no-files-found: error

  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/johnmcfarlane/simple-cpp/lint
          imageTag: 4
          runCmd: scripts/lint
