---
name: 'C++ test'

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/johnmcfarlane/simple-cpp
          imageName: ghcr.io/johnmcfarlane/simple-cpp
          imageTag: 5
          push: always

  unit-tests:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    container:
      image: ghcr.io/johnmcfarlane/simple-cpp:5
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        profile:
          - clang-debug
          - clang-release
          - clang-test
          - clang-test-fuzzer
          - clang-test-tsan
          - clang-tidy
          - gcc-debug
          - gcc-release
          - gcc-test

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run tests
        run: |
          scripts/build ~/build ${{ matrix.profile }}
          scripts/test ~/build ${{ matrix.profile }}

  lint:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    container:
      image: ghcr.io/johnmcfarlane/simple-cpp:4
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Run linter
        run: scripts/lint
